import pytest
import pandas as pd
from pages.MainPage import MainPage
from pages.ProductPage import ProductPage
from pages.ShoppingCartPage import ShoppingCartPage
from pages.SummaryPage import SummaryPage
from pages.ExtraoptionsPage import ExtraoptionsPage
from pages.CheckoutDeliveryPage import CheckoutDeliveryPage
from pages.CreateAccountPage import CreateAccountPage
from pages.LoginPage import LoginPage
from pages.SearchPage import SearchPage
import allure

@pytest.mark.usefixtures('setup')
class Test_Sale:
    xl = pd.read_excel('C:\\Users\\Dima\\Desktop\\Testing\\Python\\Zegarownia\\Fabryka_Zegarkow\\DEV\\Dane.xlsx', sheet_name="Arkusz1")
    baseURL = xl.at[0, 'Wartosc']
    productURL = xl.at[16, 'Wartosc']
    email = xl.at[1, 'Wartosc']
    username = xl.at[1, 'Wartosc']
    password = xl.at[3, 'Wartosc']
    name = xl.at[5, 'Wartosc']
    lastname = xl.at[6, 'Wartosc']
    phone = xl.at[8, 'Wartosc']
    street = xl.at[12, 'Wartosc']
    postcode = xl.at[13, 'Wartosc']
    city = xl.at[14, 'Wartosc']
    comment = xl.at[15, 'Wartosc']
    search_keyword = xl.at[10, 'Wartosc']
    paczkomat_adres = xl.at[17, 'Wartosc']
    
    @allure.title('Test sprzedaży Kurier DHL + PayU dla niezalogowanego użytkownika')
    def test_courier_dhl_payU(self):
        # pytest.skip()
        self.driver.get(self.env['PRODUCT_URL'])
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.lp = LoginPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.pp.waitForProductPage()
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.waitForExtraoptionsPageContent()
        self.ex.goToCheckoutCart()
        self.scp.waitForCartPageContent()
        self.scp.goToCheckoutDelivery()
        self.lp.waitForLoginPage()
        self.cap.clickContinueAsGuest()
        self.cdp.waitForCheckutAdressForm()
        self.cdp.setEmail(self.env['EMAIL'])
        self.cdp.setPhoneNumber(self.env['PHONE'])
        self.cdp.setFirstName(self.env['NAME'])
        self.cdp.setLastName(self.env['LASTNAME'])
        self.cdp.setStreet(self.env['STREET'])
        self.cdp.setPostcode(self.env['POSTCODE'])
        self.cdp.setCity(self.env['CITY'])
        self.cdp.waitForDeliмeryMethodsBlock()
        self.cdp.selectCourierDHL()
        self.cdp.goToCheckoutSummary()
        self.sump.waitForCheckoutSummaryPageContent()
        self.sump.selectPayU()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.waitForPayUPaymentPage()
        self.sump.AssertPayUTitle()

    @allure.title('Test sprzedaży Kurier DHL + Blik dla niezalogowanego użytkownika')
    def test_sale_2(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectCourierDHL()
        self.cdp.goToCheckoutSummary()
        self.sump.selectBlik()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertBlikTitle()

    @allure.title('Test sprzedaży Kurier DHL + Apple Pay dla niezalogowanego użytkownika')
    def test_sale_3(self):
        pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectCourierDHL()
        self.cdp.goToCheckoutSummary()
        self.sump.selectApplePay()
        self.sump.clickCheckbox1()
        self.sump.clickCheckbox2()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertPayUTitle()

    @allure.title('Test sprzedaży Kurier DHL + Raty PayU dla niezalogowanego użytkownika')
    def test_sale_4(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectCourierDHL()
        self.cdp.goToCheckoutSummary()
        self.sump.selectRatyPayU()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertPayUTitle()

    @allure.title('Test sprzedaży Kurier DHL + Raty CA dla niezalogowanego użytkownika')
    def test_sale_5(self):
        pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectCourierDHL()
        self.cdp.goToCheckoutSummary()
        self.sump.selectRatyCA()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertRatyCATitle()

    @allure.title('Test sprzedaży Kurier DHL + Twisto dla niezalogowanego użytkownika')
    def test_sale_6(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectCourierDHL()
        self.cdp.goToCheckoutSummary()
        self.sump.selectTwisto()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertPayUTitle()

    @allure.title('Test sprzedaży Kurier DHL + Przelew tradycyjny dla niezalogowanego użytkownika')
    def test_sale_7(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectCourierDHL()
        self.cdp.goToCheckoutSummary()
        self.sump.selectBankTransfer()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertSuccessPage()

    @allure.title('Test sprzedaży Kurier DHL + PayPal dla niezalogowanego użytkownika')
    def test_sale_8(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectCourierDHL()
        self.cdp.goToCheckoutSummary()
        self.sump.selectPayPal()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertPayPalTitle()

    @allure.title('Test sprzedaży Inpost paczkomaty + Przelew tradycyjny dla niezalogowanego użytkownika')
    def test_sale_8(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectInpost()
        self.cdp.SearchInpostAdress(self.paczkomat_adres)
        self.cdp.SelectPoint()
        self.cdp.ClickChooseButton()
        self.cdp.goToCheckoutSummary()
        self.sump.selectBankTransfer()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertSuccessPage()

    @allure.title('Test sprzedaży Kurier UPS Standard + Przelew tradycyjny dla niezalogowanego użytkownika')
    def test_sale_9(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.selectUpsStandard()
        self.cdp.goToCheckoutSummary()
        self.sump.selectBankTransfer()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertSuccessPage()

    @allure.title('Test sprzedaży Odbir w sklepie + Przelew tradycyjny dla niezalogowanego użytkownika')
    def test_sale_10(self):
        # pytest.skip()
        self.driver.get(self.productURL)
        self.mp = MainPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.cap = CreateAccountPage(self.driver)
        self.mp.clickAcceptCookies()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.cap.clickContinueAsGuest()
        self.cdp.setEmail(self.email)
        self.cdp.setPhoneNumber(self.phone)
        self.cdp.setFirstName(self.name)
        self.cdp.setLastName(self.lastname)
        self.cdp.setStreet(self.street)
        self.cdp.setPostcode(self.postcode)
        self.cdp.setCity(self.city)
        self.cdp.clickFreeShipping()
        self.cdp.goToCheckoutSummary()
        self.sump.selectBankTransfer()
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertSuccessPage()

    @allure.title('Test sprzedaży DHL + Przelew tradycyjny dla zalogowanego użytkownika')
    def test_sale_11(self):
        # pytest.skip()
        self.driver.get(self.baseURL)
        self.mp = MainPage(self.driver)
        self.sp = SearchPage(self.driver)
        self.pp  = ProductPage(self.driver)
        self.scp = ShoppingCartPage(self.driver)
        self.lp = LoginPage(self.driver)
        self.ex = ExtraoptionsPage(self.driver)
        self.cdp = CheckoutDeliveryPage(self.driver)
        self.sump = SummaryPage(self.driver)
        self.mp.SearchProduct(self.search_keyword)
        self.mp.clickSearchButton()
        self.sp.selectFirstItem()
        self.pp.clickAddToCartButton()
        self.ex.goToCheckoutCart()
        self.scp.goToCheckoutDelivery()
        self.lp.setUserName(self.username)
        self.lp.setUserPassword(self.password)
        self.lp.clickLoginButton()
        self.cdp.goToCheckoutSummary()
        self.sump.selectBankTransfer()
        self.sump.setComment(self.comment)
        self.sump.clickCheckbox1()
        self.sump.clickOrderAndPayButton()
        self.sump.AssertSuccessPage()


# pytest --env=stage tests\test_sale.py
# pytest --env=stage tests\test_sale.py::Test_Sale::test_courier_dhl_payU