class LoginPageLocators:
    login_page_content_xpath = '//div[@class="col-auto checkout__login"]'
    customer_account_icon_xpath = '//div[@class="header__account col"]'
    email_input_id = 'email'
    password_input_id = 'pass'
    login_button_xpath = '//button[@class="action login primary"]'
    logout_button_xpath = '//li[@class="nav item"][7]'
    notification_xpath = '//div[@class="notification-message-O6n"]'
    alert_message_xpath = '//div[@role="alert"]'

class CreateAccountPageLocators:
    create_account_button_xpath = '//a[@class="action create secondary"]'
    create_account_form_xpath = '//form[@class="form create account form-create-account scroll-disabled"]'
    name_id = 'firstname'
    lastname_id = 'lastname'
    email_id = 'email_address'
    password_input_id = 'password'
    password_conf_input_id = 'password-confirmation'
    sign_in_button_xpath = '//button[@class="action submit primary"]'
    continue_as_guest_button_xpath = '//input[@class="action continue primary"]'

class UserAccountPageLocators:
    user_account_page_content_xpath = '//div[@class="dashboard"]'
    seccess_message_xpath = '//div[@class="message-success success message"]'
    reset_password_checkbox_xpath = '//div[@class="field choice"][2]'
    current_password_id = 'current-password'
    new_password_id = 'password'
    confirm_new_password_id = 'password-confirmation'
    save_button_xpath = '//button[@type="submit" and @title="Zapisz"]'
    account_data_button_xpath = '//li[@class="nav item"][3]'

class MainPageLocators:
    main_page_content_id = 'maincontent'
    menu_kategorie_xpath = '//div[@class="mainNavStyles-link-2oO"]'
    kategorie_href_xpath = '//a[@class="categoryListStyles-link-1xd"]'
    podkategorie_href_xpath = '//a[@class="subCategoriesStyles-link-3VT"]'
    search_input_id = 'search'
    search_button_xpath = '//button[@class="action search"]'
    accept_cookies_xpath = '//a[@class="action primary" and @title="Zgadzam się"]'
    contact_form_button_xpath = '//a[@title="Kontakt"]'

class ContactPageLocators:
    contact_form_page_content_xpath = '//form[@class="form contact"]'
    contact_form_name_id = 'name'
    contact_form_email_id = 'email'
    contact_form_phone_id = 'telephone'
    contact_form_comment_id = 'comment'
    send_button_xpath = '//button[@class="action submit primary"]'

class SearchPageLocators:
    product_list_xpath = '//li[@class="item product product-item"]'
    search_result_page_xpath = '//main[@class="page-main lbx-wrapper"]'

class ProductPageLocators:
    product_page_content_xpath = '//div[@class="product-info-main"]'
    add_to_cart_button_id = 'product-addtocart-button'
    input_xpath = '//div[@class="col-12 col-md-auto select-quantity-desktop"]//child::input'
    delete_from_cart_xpath = '//span[@class="section-text-3ch" and contains(text(), "Usuń z koszyka")]'

class ExtraoptionsPageLocators:
    extraoptions_page_content_xpath = '//div[@class="row extra-options__wrapper"]'
    go_to_cart_button_xpath = '//a[@class="action primary checkout arrowed w-100"]'
    engrave_product_checkbox_xpath = '//div[@class="engraver-container"]'
    engraver_product_a_xpath = '//label[@for="engraver-A"]'
    engraver_product_b_xpath = '//label[@for="engraver-B"]'
    engraver_product_c_xpath = '//label[@for="engraver-C"]'
    engraver_product_input_id = 'engraver-message'
    order_engraver_button_xpath = '//div[@class="extra-options__footer"]//button[@form="engraver-form"]'
    engrave_plate_checkbox_xpath = '//div[@class="engraver-plate-container"]'
    engrave_plate_a_xpath = '//label[@for="engraver-plate-A"]'
    engrave_plate_b_xpath = '//label[@for="engraver-plate-B"]'
    engrave_plate_c_xpath = '//label[@for="engraver-plate-C"]'
    engrave_plate_input_id = 'engraver-plate-message'
    engrave_popup_area_xpath = '//div[@class="extra-options__inner engraver-modal"]'
    plate_popup_area_xpath = '//div[@class="extra-options__inner engraver-plate-modal"]'
    order_plate_button_xpath = '//div[@class="extra-options__inner engraver-plate-modal"]//button[@class="action primary"]'
    bracelet_checkbox_xpath = '//div[@class="bracelet-container"]'
    gift_wrap_checkbox_xpath = '//div[@class="gift-wrap-container"]'
    insurance_checkbox_xpath = '//div[@class="insurance-container"]'

class ShoppingCartPageLocators:
    cart_page_content_xpath = '//div[@class="row cart-container"]'
    product_input_count_xpath = '//input[@data-role="cart-item-qty"]'
    go_to_order_button_xpath = '//button[@class="action primary arrowed checkout"]'

class CheckoutDeliveryLocators:
    checkout_adress_form_xpath = '//li[@class="checkout-shipping-address"]'
    email_input_id = 'customer-email'
    phone_input_xpath = '//input[@name="telephone"]'
    firstname_input_xpath = '//input[@name="firstname"]'
    lastname_input_xpath = '//input[@name="lastname"]'
    street_input_xpath = '//input[@name="street[0]"]'
    postcode_input_xpath = '//input[@name="postcode"]'
    city_input_xpath = '//input[@name="city"]'
    delivery_methods_xpath = '//div[@class="checkout-shipping-method"]'
    proceed_to_summary_button_id = 'summary-shipping-button'
    courier_dhl_xpath = '//tr[@class="method--courier_dhl_dhl24pl"]'
    parcelshop_dhl_xpath = '//tr[@class="method--parcelshop_dhl_dhl24pl"]'
    parcelshop_input_id = 'map-input'
    parcelshop_point_id = 'nearest_0'
    inpost_xpath = '//tr[@class="method--inpost_inpost"]'
    inpost_input_id = 'easypack-search'
    inpost_point_xpath = '//a[@href="#WRO06N"]'
    inpost_select_button_xpath = '//a[@class="select-link"]'
    ups_standard_xpath = '//tr[@class="method--ups_courier_ups_courier"]'
    freeshipping_xpath = '//tr[@class="method--freeshipping_freeshipping"]'

class SummaryPageLocators:
    summary_page_content_xpath = '//div[@class="checkout-container row"]'
    payU_xpath = '//div[@class="tr payment-method payu-payment"]'
    blik_xpath = '//div[@class="tr payment-method payu-payment"][1]'
    apple_pay_xpath = '//div[@class="tr payment-method payu-payment"][2]'
    raty_payU_xpath = '//div[@class="tr payment-method payu-payment payu-installments"]'
    raty_CA_xpath = '//div[@class="tr"][1]'
    twisto_xpath = '//div[@class="tr payment-method payu-payment twisto"]'
    bank_transfer_xpath = '//div[@class="tr"][2]'
    paypal_xpath = '//div[@class="tr"][4]'
    agreement_1_id = 'agreement__3'
    agreement_2_id = 'agreement__4'
    order_and_pay_button_xpath = '//button[@class="action primary w-100"]'

class PaymentPageLocators:
    paU_page_content_xpath = '//div[@class="app-container"]'